MemorizeThem/MemorizeThem/urls.py
from models_test import views
from django.contrib import admin
from django.conf.urls import url
from django.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('user_authorization.urls')),
    url(r'^contacts/', include('models_test.urls')),
    url(r'^$', views.title, name='title')
]

MemorizeThem/google_auth/urls.py
from django.conf.urls import url
from google_auth import views

urlpatterns = [
    url(r'^sync/', views.login, name='login'),
]

MemorizeThem/models_test/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from models_test import views

app_name = 'models_test'

urlpatterns = [
    url(r'^$', views.contacts, name='contacts'),
    url(r'^create/', views.create_contact, name='create_contact'),
    url(r'^delete/(?P<contact_id>\d+)/$', views.delete_contact, name='delete_contact'),
    url(r'^edit/(?P<contact_id>\d+)/$', views.edit_contact, name='edit_contact'),
    url(r'^get/(?P<contact_id>\d+)/$', views.contact, name='contact'),
    url(r'^google_auth/', include('google_auth.urls')),
    url(r'^delete/all/$', views.delete_all_contacts, name='delete_all_contacts'),
    url(r'^filter/country/$', views.filter_by_country, name='filter_by_country'),
    url(r'^filter/city/$', views.filter_by_city, name='filter_by_city'),
    url(r'^filter/job/$', views.filter_by_job, name='filter_by_job')
]

MemorizeThem/models_test/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Contact(models.Model):
    id = models.CharField(primary_key=True, serialize=False, verbose_name='ID', max_length=128)
    name = models.CharField(max_length=128, default="", null=True, blank=True)
    surname = models.CharField(max_length=128, default="", null=True, blank=True)
    patronymic = models.CharField(max_length=128, default="", null=True, blank=True)
    email = models.EmailField(default="", null=True, blank=True)
    mobile_phone = models.CharField(max_length=32, default="", null=True, blank=True)
    work_phone = models.CharField(max_length=32, default="", null=True, blank=True)
    home_phone = models.CharField(max_length=32, default="", null=True, blank=True)
    birthday = models.DateField(default=None, null=True, blank=True)
    gender = models.CharField(max_length=16, default="", null=True, blank=True)
    biography = models.CharField(max_length=10000, default="", null=True, blank=True)
    interests = models.CharField(max_length=1000, default="", null=True, blank=True)
    photo = models.URLField()
    job = models.CharField(max_length=250, default="", null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # needs to be unique
    postal_code = models.CharField(max_length=64, default="", null=True, blank=True)
    country = models.CharField(max_length=64, default="", null=True, blank=True)
    city = models.CharField(max_length=64, default="", null=True, blank=True)
    street = models.CharField(max_length=64, default="", null=True, blank=True)
    house_number = models.CharField(max_length=16, default="", null=True, blank=True)
    flat_number = models.CharField(max_length=16, default="", null=True, blank=True)

    def __unicode__(self):
        return '{0} {1} {2}'.format(
            self.name, self.surname, self.patronymic
        )


from django.forms import ModelForm


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'surname', 'patronymic', 'country', 'city', 'flat_number', 'house_number',
                  'email', 'mobile_phone', 'work_phone', 'home_phone', 'job',
                  'biography', 'interests', 'photo']

MemorizeThem/models_test/views.py
from django.http import HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from models_test.models import Contact, ContactForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def title(request):
    return render(request, 'title.html')


@login_required(login_url='/auth/login/')
def contacts(request):
    return render_to_response('contacts.html', {'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id),
                                                'user': auth.get_user(request)})


def contact(request, contact_id=1):
    return render_to_response('contact.html', {'contact': Contact.objects.get(id=contact_id),
                                               'user': auth.get_user(request)})


def delete_contact(request, contact_id):
    Contact.objects.filter(id=contact_id).delete()
    return redirect('/contacts/')


def delete_all_contacts(request):
    Contact.objects.filter(owner_id=auth.get_user(request).id).delete()
    return redirect('/contacts/')


@login_required(login_url='/auth/login/')
def create_contact(request):
    if request.POST:
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner_id = auth.get_user(request).id
            instance.save()
            return redirect('models_test:contacts')
    else:
        form = ContactForm()

    return render(request, 'create_contact.html', {'form': form})


@login_required(login_url='/auth/login/')
def edit_contact(request, contact_id):
    if request.POST:
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            print(contact_id)

            contact = Contact.objects.get(id=contact_id)
            contact.id = contact_id
            contact.name = form.cleaned_data['name']
            contact.surname = form.cleaned_data['surname']
            contact.patronymic = form.cleaned_data['patronymic']
            contact.country = form.cleaned_data['country']
            contact.city = form.cleaned_data['city']
            contact.flat_number = form.cleaned_data['flat_number']
            contact.house_number = form.cleaned_data['house_number']
            contact.email = form.cleaned_data['email']
            contact.mobile_phone = form.cleaned_data['mobile_phone']
            contact.work_phone = form.cleaned_data['work_phone']
            contact.home_phone = form.cleaned_data['home_phone']
            contact.job = form.cleaned_data['job']
            contact.biography = form.cleaned_data['biography']
            contact.interests = form.cleaned_data['interests']
            contact.photo = form.cleaned_data['photo']

            contact.save()

            return redirect('models_test:contacts')
    else:
        contact = Contact.objects.get(id=contact_id)
        data = {
            'name': contact.name,
            'surname': contact.surname,
            'patronymic': contact.patronymic,
            'country': contact.country,
            'city': contact.city,
            'flat_number': contact.flat_number,
            'house_number': contact.house_number,
            'email': contact.email,
            'mobile_phone': contact.mobile_phone,
            'work_phone': contact.work_phone,
            'home_phone': contact.home_phone,
            'job': contact.job,
            'biography': contact.biography,
            'interests': contact.interests,
            'photo': contact.photo,
        }
        form = ContactForm(initial=data)

    return render(request, 'edit_contact.html', {'form': form,
                                                 'contact_id': contact_id})


def filter_by_city(request):
    if request.POST:
        data = request.POST.get('filter_field')
        print(data)
        return render(request, 'contacts.html', {'city': data,
                                                 'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})
    else:
        return render(request, 'filter.html', {'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})


def filter_by_country(request):
    if request.POST:
        data = request.POST.get('filter_field')
        print(data)
        return render(request, 'contacts.html', {'country': data,
                                                 'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})
    else:
        return render(request, 'filter.html', {'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})


def filter_by_job(request):
    if request.POST:
        data = request.POST.get('filter_field')
        print(data)
        return render(request, 'contacts.html', {'job': data,
                                                 'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})
    else:
        return render(request, 'filter.html', {'contacts': Contact.objects.filter(owner_id=auth.get_user(request).id)})

MemorizeThem/models_test/templates/contact.html
{% extends 'main.html' %}

{% block contact %}
    {% if contact %}
        <div style="margin: 5px; position: relative;">
            <img src="{{contact.photo}}" style="border-radius: 10px;">
        </div>
        <table>
            <tbody>
                <tr>
                    <td>Name</td>
                    {% if contact.name %}
                        <td>{{ contact.name }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Surname</td>
                    {% if contact.surname %}
                        <td>{{ contact.surname }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Patronymic</td>
                    {% if contact.patronymic %}
                        <td>{{ contact.patronymic }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Address</td>

                    {% if contact.address.country or contact.address.city or contact.address.street or address.house_number or contact.address.flat_number %}
                        <td>
                            {{ contact.address.country }},
                            {{ contact.address.city }},
                            {{ contact.address.street }},
                            {{ contact.address.house_number }},
                            {{ contact.address.flat_number }}
                        </td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Email</td>
                    {% if contact.email %}
                        <td>{{ contact.email }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Phones</td>

                    {% if contact.mobile_phone or contact.work_phone or contact.home_phone %}
                        <td>
                            <p>Mobile phone: {{ contact.mobile_phone }}</p>
                            <p>Work phone: {{ contact.work_phone }}</p>
                            <p>Home phone: {{ contact.home_phone }}</p>
                        </td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Job</td>
                    {% if contact.job %}
                        <td>{{ contact.job }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Biography</td>
                    {% if contact.biography %}
                        <td>{{ contact.biography }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
                <tr>
                    <td>Interests</td>
                    {% if contact.interests %}
                        <td>{{ contact.interests }}</td>
                    {% else %}
                        <td>Nothing here</td>
                    {% endif %}
                </tr>
            </tbody>
        </table>
        <a href="/contacts/edit/{{contact.id}}/" class="button" type="button" style="background-color: #0c3d5d; width: 100%; margin-bottom: 4px;">Edit</a>
        <a href="/contacts/delete/{{contact.id}}/" class="button" type="button" style="background-color: #cc1111; width: 100%"
                    onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
        {% else %}
            <strong>There are no contacts to present.</strong>
    {% endif %}
{% endblock %}

MemorizeThem/models_test/templates/contacts.html
{% extends 'main.html' %}

{% block contact %}

<div>
    <h3 style="display: inline-block">List of your friends</h3>
    <a href="/contacts/google_auth/sync/" style="display: inline-block; float: right" type="button" class="button">Import contacts</a>
    <a href="/contacts/create/" style="margin-right: 5px; display: inline-block; float: right" type="button" class="button">+ Create contact</a>
    <a href="/contacts/delete/all/" style="background-color: #cc1111; margin-right: 5px; display: inline-block; float: right" type="button" class="button">Delete all contacts</a>

<div class="dropdown" style="float: right; display: inline-block">
  <button class="button dropbtn" type="button" style="margin-right: 5px;">Sort by</button>
  <div class="dropdown-content">
    <a href="/contacts/filter/country">Country</a>
    <a href="/contacts/filter/city">City</a>
    <a href="/contacts/filter/job">Job</a>
  </div>
</div>
    {% block filter %}{% endblock %}
    <br>
    <br>
</div>

<div class="grid-x grid-margin-x small-up-1 medium-up-2 large-up-3">
    {% if contacts %}
        {% if country %}
            {% for contact in contacts %}
                {% if contact.country == country %}
                    <div class="cell">
                            <div class="callout" style="height: 95%;">
                                <p align="center" style="font-size: x-large;">{{contact.name}} {{contact.patronymic}}</p>
                                <div align="center" style="align-items: center; margin: 5px; position: relative;">
                                    <img src="{{contact.photo}}" style="border-radius: 10px;">
                                </div>
                                <p align="center" class="subheader">{{contact.mobile_phone}}</p>
                                <p align="center" class="subheader">{{contact.email}}</p>
                                <a href="get/{{contact.id}}/" class="success button" style="width: 100%;">Details</a>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

        {% elif city %}
            {% for contact in contacts %}
                {% if contact.city == city %}
                    <div class="cell">
                        <div class="callout" style="height: 95%;">
                            <p align="center" style="font-size: x-large;">{{contact.name}} {{contact.patronymic}}</p>
                            <div align="center" style="align-items: center; margin: 5px; position: relative;">
                                <img src="{{contact.photo}}" style="border-radius: 10px;">
                            </div>
                            <p align="center" class="subheader">{{contact.mobile_phone}}</p>
                            <p align="center" class="subheader">{{contact.email}}</p>
                            <a href="get/{{contact.id}}/" class="success button" style="width: 100%;">Details</a>
                    </div>
                  </div>
                {% endif %}
            {% endfor %}

        {% elif job %}
            {% for contact in contacts %}
                {% if contact.job == job %}
                    <div class="cell">
                        <div class="callout" style="height: 95%;">
                            <p align="center" style="font-size: x-large;">{{contact.name}} {{contact.patronymic}}</p>
                            <div align="center" style="align-items: center; margin: 5px; position: relative;">
                                <img src="{{contact.photo}}" style="border-radius: 10px;">
                            </div>
                            <p align="center" class="subheader">{{contact.mobile_phone}}</p>
                            <p align="center" class="subheader">{{contact.email}}</p>
                            <a href="get/{{contact.id}}/" class="success button" style="width: 100%;">Details</a>
                    </div>
                  </div>
                {% endif %}
            {% endfor %}

        {% else %}
            {% for contact in contacts %}
                <div class="cell">
                        <div class="callout" style="height: 95%;">
                            <p align="center" style="font-size: x-large;">{{contact.name}} {{contact.patronymic}}</p>
                            <div align="center" style="align-items: center; margin: 5px; position: relative;">
                                <img src="{{contact.photo}}" style="border-radius: 10px;">
                            </div>
                            <p align="center" class="subheader">{{contact.mobile_phone}}</p>
                            <p align="center" class="subheader">{{contact.email}}</p>
                            <a href="get/{{contact.id}}/" class="success button" style="width: 100%;">Details</a>
                    </div>
                  </div>
            {% endfor %}

        {% endif %}

    {% else %}
            <strong>There are no contacts to present.</strong>
    {% endif %}

</div>

{% endblock %}

MemorizeThem/models_test/templates/create_contact.html
{% extends 'main.html' %}

{% block contact %}

    <h2>Create new contact</h2>
    <form class="site-form" action="{% url 'models_test:create_contact' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" style="width: 100%" value="Create">
    </form>

{% endblock %}

MemorizeThem/models_test/templates/edit_contact.html
{% extends 'main.html' %}

{% block contact %}

<div style="max-width: 75%">
    <form class="site-form" action="/contacts/edit/{{contact_id}}/" method="post">
        {% csrf_token %}
        {{ form }}

        <input type="submit" class="button" style="width: 100%" value="Save changes">
    </form>
</div>

{% endblock %}

MemorizeThem/models_test/templates/filter.html
{% extends 'contacts.html' %}


{% block filter %}

    <div style="display: inline-block; float: right; margin-right: 5px; margin-top: 1px">
      <form method="post">
        {% csrf_token %}
        <input type="text" style="position: relative; alignment: center" name="filter_field">
        <input type="submit" style="display: none">
      </form>
    </div>

{% endblock %}